language: node_js
node_js:
  - 7.7
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install bower -g
  - bower install
after_install:
  - curl -X PURGE https://coveralls.io/repos/github/blixit/galgas-web-editor/badge.svg
